config/routes.rb
Rails.application.routes.draw do
  get 'normalisasi_data/data_normalize'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/normalisasi_data_controller.rb
class NormalisasiDataController < ApplicationController
  def data_normalize
  	@data = []
  	file = File.new("#{Rails.root}/public/1_normalisasi_data/#{params[:data_txt]}.txt", "r")
    while (line = file.gets)
    	if line != "\r\n"
        if params[:data_txt] == "iris"
  	    	data_txt = line.split(",")[0..3]
        else
          data_txt = line.split("\t")[0..4]
        end
	    	data_txt = data_txt.map { |e| e.to_f }
	    	@data.push(data_txt)
    	end
    end
    file.close

    @min_max_datas = count_min_max(@data, @data.first.length)
    @zscore_datas = count_zscore(@data, @data.first.length)
    @decimal_scaling_datas = count_decimal_scaling(@data, @data.first.length)
    @sigmoidal_datas = count_sigmoidal(@data, @data.first.length)
    @softmax_datas = count_softmax(@data, @data.first.length)
  end

  private
  def re_array(datas, count_column)
    @selected_data = []
    count_column.times do |i|
      data2 = []
      datas.each do |data|
        data2.push(data[i])
      end
      @selected_data.push(data2)
    end

    return @selected_data
  end

  def count_min_max(datas, count_column)
    newmin = 0
    newmax = 1
    @selected_data = re_array(datas, count_column)

    @minmax_value = []
    count_column.times do |idx|
      @minmax_value.push(@selected_data[idx].minmax)
    end

    @min_max_datas = []
    datas.each do |data|
      newdata = []
      data.each_with_index do |data2, jdx|
        newdata.push( ( (data2-@minmax_value[jdx][0]) * (newmax - newmin) ) / ( (@minmax_value[jdx][1] - @minmax_value[jdx][0]) + newmin ) )
      end

      @min_max_datas.push(newdata)
    end

    return @min_max_datas
  end

  def count_zscore(datas, count_column)
    @selected_data = re_array(datas, count_column)

    @avg_datas = []
    @std_deviation = []
    @selected_data.each do |data|
      total = 0
      data.each do |data2|
        total += data2
      end
      avg = total/data.length

      total_kuadrat = 0
      data.each do |data2|
        total_kuadrat += (data2 - avg) ** 2
      end
      variance = total_kuadrat / (data.length - 1)
      std_dev = Math.sqrt(variance)
      @avg_datas.push( avg )
      @std_deviation.push( std_dev )
    end

    @zscore_datas = []
    datas.each do |data|
      newdata = []
      data.each_with_index do |data2, jdx|
        newdata.push( (data2 - @avg_datas[jdx])/@std_deviation[jdx] )
      end
      @zscore_datas.push( newdata )
    end

    return @zscore_datas
  end

  def count_decimal_scaling(datas, count_column)
    if params[:data_txt] == "iris"
      pengali = [-1, -1, -1, -1]
    else
      pengali = [2, 1, 0, 1, 1]
    end

    decimal_scaling_datas = [pengali]

    datas.each do |data|
      decimal_scaling = []
      data.each_with_index do |data2, jdx|
        decimal_scaling.push( data2 / ( 10**(pengali[jdx]) ) )
      end

      decimal_scaling_datas.push( decimal_scaling )
    end

    return decimal_scaling_datas
  end

  def count_sigmoidal(datas, count_column)
    data_zscore = count_zscore(datas, count_column)

    sigmoidal_datas = []
    data_zscore.each do |zscores|
      sigmoidal = []
      zscores.each do |zscore|
        sigmoidal.push( (1 - (Math.exp(-zscore)))/ (1 + (Math.exp(-zscore))) )
      end
      sigmoidal_datas.push(sigmoidal)
    end

    return sigmoidal_datas
  end

  def count_softmax(datas, count_column)
    dev_linier = 1

    @selected_data = re_array(datas, count_column)

    @avg_datas = []
    @std_deviation = []
    @selected_data.each do |data|
      total = 0
      data.each do |data2|
        total += data2
      end
      avg = total/data.length

      total_kuadrat = 0
      data.each do |data2|
        total_kuadrat += (data2 - avg) ** 2
      end
      variance = total_kuadrat / (data.length - 1)
      std_dev = Math.sqrt(variance)
      @avg_datas.push( avg )
      @std_deviation.push( std_dev )
    end

    softmax_datas = []
    datas.each do |data|
      softmax = []
      data.each_with_index do |data2, jdx|
        transfdata = (data2 - @avg_datas[jdx]) / (dev_linier * (@std_deviation[jdx] / (2 * 3.14)) )
        softmax.push( 1/(1 + Math.exp(-transfdata)) )
      end

      softmax_datas.push( softmax )
    end

    return softmax_datas
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/normalisasi_data_helper.rb
module NormalisasiDataHelper
end

app/views/layouts/_application_header.html.erb
<header class="main-header">

  <!-- Logo -->
  <a href="<%= root_path %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>D</b>M</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Data</b>Mining</span>
  </a>

  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i>
            <span class="label label-warning">10</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 10 notifications</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                    <i class="fa fa-users text-aqua"></i> 5 new members joined today
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                    page and may cause design problems
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> 5 new members joined
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-user text-red"></i> You changed your username
                  </a>
                </li>
              </ul>
            </li>
            <li class="footer"><a href="#">View all</a></li>
          </ul>
        </li>
        <!-- Tasks: style can be found in dropdown.less -->
        <li class="dropdown tasks-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-flag-o"></i>
            <span class="label label-danger">9</span>
          </a>
          <ul class="dropdown-menu">
            <li class="header">You have 9 tasks</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Design some buttons
                      <small class="pull-right">20%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">20% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Create a nice theme
                      <small class="pull-right">40%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">40% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Some task I need to do
                      <small class="pull-right">60%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">60% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                  <a href="#">
                    <h3>
                      Make beautiful transitions
                      <small class="pull-right">80%</small>
                    </h3>
                    <div class="progress xs">
                      <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                        <span class="sr-only">80% Complete</span>
                      </div>
                    </div>
                  </a>
                </li>
                <!-- end task item -->
              </ul>
            </li>
            <li class="footer">
              <a href="#">View all tasks</a>
            </li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="/img/user.png" class="user-image" alt="User Image">
            <span>Dimas Jabbar Karim<i class="caret"></i></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <img src="/img/user.png" class="img-circle" alt="User Image">

              <p>
                Dimas Jabbar Karim
                <small>RoR Developer</small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-primary btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <%= link_to "#", :method=>'delete', class: "btn btn-default btn-flat", title: "Sign out" do%>
                  Sign out
                <% end %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>

  </nav>
</header>

app/views/layouts/_application_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/img/user.png" class="img-circle" alt="User Image">
      </div>
      <div class="pull-left info">
        <p>Dimas Jabbar Karim</p>
        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-database"></i>
          <span>Normalisasi Data</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li><a href="<%= normalisasi_data_data_normalize_path(data_txt: "iris") %>"><i class="fa fa-file"></i> Data Iris</a></li>
          <li><a href="<%= normalisasi_data_data_normalize_path(data_txt: "newthyroid") %>"><i class="fa fa-file"></i> Data Newthyroid</a></li>
        </ul>
      </li>
      <li class="header">REPORTS</li>
      <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataMining</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  	<!-- Ionicons -->
  	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  </head>

  <body class="skin-red sidebar-mini">
    <div class="wrapper">
	  <%= render "layouts/application_header" %>
	  <%= render "layouts/application_sidebar" %>
	  <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <% flash.each do |name, msg| %>
          <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
            <%= msg %>	            
          <% end %>
        <% end %>
        <%= yield %>
      <!-- /.content -->
      </div>

	  <footer class="main-footer">
		<div class="pull-right hidden-xs">
		  <b>Version</b> 1.0.0
		</div>
		<strong>Copyright &copy; 2017 <a href="http://dijekarim.com">Dijekarim</a>.</strong> All rights reserved.
	  </footer>
	</div>
  </body>
</html>

app/views/normalisasi_data/data_normalize.html.erb
<section class="content-header">
  <h1> Normalisasi Data
    <small><%= params[:data_txt].capitalize %></small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Normalisasi Data</a></li>
    <li class="active">Data <%= params[:data_txt].capitalize %></li>
  </ol>
</section>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
	  <div class="nav-tabs-custom">
	    <ul class="nav nav-tabs">
	      <li class="active"><a href="#tab_1" data-toggle="tab" aria-expanded="true">Min - Max</a></li>
	      <li class=""><a href="#tab_2" data-toggle="tab" aria-expanded="false">Z-Score</a></li>
	      <li><a href="#tab_3" data-toggle="tab">Decimal Scaling</a></li>
	      <li><a href="#tab_4" data-toggle="tab">Sigmoidal</a></li>
	      <li><a href="#tab_5" data-toggle="tab">Softmax</a></li>
	    </ul>
	    <div class="tab-content">
	      <div class="tab-pane active" id="tab_1">
	          <img src="/1_normalisasi_data/min_max.png">
	          <table class="table table-hover">
	          	<thead>
	          	  <th>No.</th>
	          	  <% @min_max_datas.first.each_with_index do |colum, jdx| %>
	          	  	<th>Column <%= jdx+1 %></th>
	          	  <% end %>
	          	</thead>
	            <tbody>
	              <% @min_max_datas.each_with_index do |data, idx| %>
	                <tr>
	                  <td><%= idx+1 %></td>
	                  <% data.each do |data2| %>
	                  	<td><%= number_with_precision(data2, precision: 3) %> </td>
	                  <% end %>
	                </tr>
	              <% end %>
	            </tbody>
	          </table>
	      </div> <!-- /.tab-pane -->

	      <div class="tab-pane" id="tab_2">
	        <img src="/1_normalisasi_data/zscore.png">
	        <table class="table table-hover">
	          	<thead>
	          	  <th>No.</th>
	          	  <% @zscore_datas.first.each_with_index do |colum, jdx| %>
	          	  	<th>Column <%= jdx+1 %></th>
	          	  <% end %>
	          	</thead>
	            <tbody>
	              <% @zscore_datas.each_with_index do |data, idx| %>
	                <tr>
	                  <td><%= idx+1 %></td>
	                  <% data.each do |data2| %>
	                  	<td><%= number_with_precision(data2, precision: 3) %> </td>
	                  <% end %>
	                </tr>
	              <% end %>
	            </tbody>
            </table>
	      </div> <!-- /.tab-pane -->

	      <div class="tab-pane" id="tab_3">
	      	<img src="/1_normalisasi_data/decimal_scaling.png">
	        <table class="table table-hover">
	          	<thead>
	          	  <th>No.</th>
	          	  <% @decimal_scaling_datas.first.each_with_index do |colum, jdx| %>
	          	  	<th>Column <%= jdx+1 %> <br> i = <%= colum %> </th>
	          	  <% end %>
	          	</thead>
	            <tbody>
	              <% @decimal_scaling_datas.each_with_index do |data, idx| %>
	                <tr>
	                  <% if idx != 0 %>
						<td><%= idx %></td>
		                <% data.each do |data2| %>
		                  <td><%= data2.round(2) %> </td>
		                <% end %>
	                  <% end %>
	                </tr>
	              <% end %>
	            </tbody>
            </table>
	      </div> <!-- /.tab-pane -->

	      <div class="tab-pane" id="tab_4">
	      	<img src="/1_normalisasi_data/sigmoidal.png">
	        <table class="table table-hover">
	          	<thead>
	          	  <th>No.</th>
	          	  <% @sigmoidal_datas.first.each_with_index do |colum, jdx| %>
	          	  	<th>Column <%= jdx+1 %></th>
	          	  <% end %>
	          	</thead>
	            <tbody>
	              <% @sigmoidal_datas.each_with_index do |data, idx| %>
	                <tr>
	                  <td><%= idx+1 %></td>
	                  <% data.each do |data2| %>
	                  	<td><%= number_with_precision(data2, precision: 3) %> </td>
	                  <% end %>
	                </tr>
	              <% end %>
	            </tbody>
            </table>
	      </div> <!-- /.tab-pane -->

	      <div class="tab-pane" id="tab_5">
	      	<img src="/1_normalisasi_data/softmax.png">
	        <table class="table table-hover">
	          	<thead>
	          	  <th>No.</th>
	          	  <% @softmax_datas.first.each_with_index do |colum, jdx| %>
	          	  	<th>Column <%= jdx+1 %></th>
	          	  <% end %>
	          	</thead>
	            <tbody>
	              <% @softmax_datas.each_with_index do |data, idx| %>
	                <tr>
	                  <td><%= idx+1 %></td>
	                  <% data.each do |data2| %>
	                  	<td><%= number_with_precision(data2, precision: 4) %> </td>
	                  <% end %>
	                </tr>
	              <% end %>
	            </tbody>
            </table>
	      </div> <!-- /.tab-pane -->
	    </div>
	    <!-- /.tab-content -->
	  </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<section class="content-header">
  <h1> Dashboard
    <!-- <small>Version 2.0</small> -->
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Dashboard</li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
  <!-- Info boxes -->
  <div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">CPU Traffic</span>
          <span class="info-box-number">90<small>%</small></span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Likes</span>
          <span class="info-box-number">41,410</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">Sales</span>
          <span class="info-box-number">760</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

        <div class="info-box-content">
          <span class="info-box-text">New Members</span>
          <span class="info-box-number">2,000</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->

  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Monthly Recap Report</h3>

          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
            <div class="btn-group">
              <button type="button" class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-wrench"></i></button>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
            </div>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="row">
            <div class="col-md-8">
              <p class="text-center">
                <strong>Sales: 1 Jan, 2014 - 30 Jul, 2014</strong>
              </p>

              <div class="chart">
                <!-- Sales Chart Canvas -->
                <canvas id="salesChart" style="height: 180px;"></canvas>
              </div>
              <!-- /.chart-responsive -->
            </div>
            <!-- /.col -->
            <div class="col-md-4">
              <p class="text-center">
                <strong>Goal Completion</strong>
              </p>

              <div class="progress-group">
                <span class="progress-text">Add Products to Cart</span>
                <span class="progress-number"><b>160</b>/200</span>

                <div class="progress sm">
                  <div class="progress-bar progress-bar-aqua" style="width: 80%"></div>
                </div>
              </div>
              <!-- /.progress-group -->
              <div class="progress-group">
                <span class="progress-text">Complete Purchase</span>
                <span class="progress-number"><b>310</b>/400</span>

                <div class="progress sm">
                  <div class="progress-bar progress-bar-red" style="width: 80%"></div>
                </div>
              </div>
              <!-- /.progress-group -->
              <div class="progress-group">
                <span class="progress-text">Visit Premium Page</span>
                <span class="progress-number"><b>480</b>/800</span>

                <div class="progress sm">
                  <div class="progress-bar progress-bar-green" style="width: 80%"></div>
                </div>
              </div>
              <!-- /.progress-group -->
              <div class="progress-group">
                <span class="progress-text">Send Inquiries</span>
                <span class="progress-number"><b>250</b>/500</span>

                <div class="progress sm">
                  <div class="progress-bar progress-bar-yellow" style="width: 80%"></div>
                </div>
              </div>
              <!-- /.progress-group -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!-- ./box-body -->
        <div class="box-footer">
          <div class="row">
            <div class="col-sm-3 col-xs-6">
              <div class="description-block border-right">
                <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                <h5 class="description-header">$35,210.43</h5>
                <span class="description-text">TOTAL REVENUE</span>
              </div>
              <!-- /.description-block -->
            </div>
            <!-- /.col -->
            <div class="col-sm-3 col-xs-6">
              <div class="description-block border-right">
                <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                <h5 class="description-header">$10,390.90</h5>
                <span class="description-text">TOTAL COST</span>
              </div>
              <!-- /.description-block -->
            </div>
            <!-- /.col -->
            <div class="col-sm-3 col-xs-6">
              <div class="description-block border-right">
                <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                <h5 class="description-header">$24,813.53</h5>
                <span class="description-text">TOTAL PROFIT</span>
              </div>
              <!-- /.description-block -->
            </div>
            <!-- /.col -->
            <div class="col-sm-3 col-xs-6">
              <div class="description-block">
                <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                <h5 class="description-header">1200</h5>
                <span class="description-text">GOAL COMPLETIONS</span>
              </div>
              <!-- /.description-block -->
            </div>
          </div>
          <!-- /.row -->
        </div>
        <!-- /.box-footer -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->

</section>